name: Run tests on PR

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: Test on node $ and $

    runs-on: $

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js $
      uses: actions/setup-node@v1
      with:
        node-version: $

    - name: Run tests and linting
      run: |
        npm ci
        npm run build
        npm test
      env:
        CI: true

